if 'transformer' not in globals():
    from mage_ai.data_preparation.decorators import transformer
if 'test' not in globals():
    from mage_ai.data_preparation.decorators import test


@transformer
def transform(stock_data, *args, **kwargs):
    """
    Replace stock symbols with unique names in the stock_data dataframe.

    Args:
        stock_data (pd.DataFrame): DataFrame containing stock data with a 'stock_symbol' column.

    Returns:
        pd.DataFrame: DataFrame with stock symbols replaced by unique names.
    """
    # Create a mapping of stock symbols to unique names
    symbol_mapping = {
    "AAPL": "Apple Inc.",
    "GOOG": "Alphabet Inc.",
    "MSFT": "Microsoft Corporation",
    "AMZN": "Amazon.com Inc.",
    "TSLA": "Tesla Inc.",
    "NVDA": "NVIDIA Corporation",
    "CRM": "Salesforce.com Inc.",
    "ADBE": "Adobe Inc.",
    "INTC": "Intel Corporation",
    "CSCO": "Cisco Systems Inc.",
    "IBM": "International Business Machines Corporation",
    "ORCL": "Oracle Corporation",
    "SAP": "SAP SE",
    "HPQ": "HP Inc.",
    "DELL": "Dell Technologies Inc.",
    "TXN": "Texas Instruments Incorporated",
    "QCOM": "QUALCOMM Incorporated",
    "AVGO": "Broadcom Inc.",
    "MRVL": "Marvell Technology Group Ltd.",
    "ADI": "Analog Devices Inc.",
    "V": "Visa Inc.",
    "BRK.B": "Berkshire Hathaway Inc.",
    "NFLX": "Netflix Inc.",
    "PYPL": "PayPal Holdings Inc.",
    "JPM": "JPMorgan Chase & Co.",
    "JNJ": "Johnson & Johnson",
    "PG": "Procter & Gamble Company",
    "MA": "Mastercard Incorporated",
    "DIS": "The Walt Disney Company",
    "UNH": "UnitedHealth Group Incorporated",
    "VZ": "Verizon Communications Inc.",
    "BAC": "Bank of America Corporation",
    "XOM": "Exxon Mobil Corporation",
    "KO": "The Coca-Cola Company",
    "PFE": "Pfizer Inc.",
    "ABT": "Abbott Laboratories",
    "MRK": "Merck & Co. Inc.",
    "NKE": "NIKE Inc.",
    "ACN": "Accenture plc",
    "MCD": "McDonald's Corporation",
    "WMT": "Walmart Inc.",
    "T": "AT&T Inc.",
    "C": "Citigroup Inc.",
    "CVX": "Chevron Corporation",
    "COST": "Costco Wholesale Corporation",
    "GILD": "Gilead Sciences Inc.",
    "ABBV": "AbbVie Inc.",
    "BMY": "Bristol-Myers Squibb Company",
    "DHR": "Danaher Corporation",
    "LLY": "Eli Lilly and Company",
    "UPS": "United Parcel Service Inc.",
    "SBUX": "Starbucks Corporation",
    "CAT": "Caterpillar Inc.",
    "MDLZ": "Mondelez International Inc.",
    "MMM": "3M Company",
    "HON": "Honeywell International Inc.",
    "LIN": "Linde plc",
    "LOW": "Lowe's Companies Inc.",
    "AMGN": "Amgen Inc.",
    "MO": "Altria Group Inc.",
    "BKNG": "Booking Holdings Inc.",
    "TMO": "Thermo Fisher Scientific Inc.",
    "CHTR": "Charter Communications Inc.",
    "WFC": "Wells Fargo & Company",
    "NEE": "NextEra Energy Inc.",
    "AAP": "Advance Auto Parts Inc.",
    "LMT": "Lockheed Martin Corporation",
    "ZTS": "Zoetis Inc.",
    "ADP": "Automatic Data Processing Inc.",
    "MET": "MetLife Inc.",
    "UNP": "Union Pacific Corporation",
    "NOW": "ServiceNow Inc.",
    "CME": "CME Group Inc.",
    "GE": "General Electric Company",
    "AMD": "Advanced Micro Devices Inc.",
    "INTU": "Intuit Inc.",
    "MU": "Micron Technology Inc.",
    "ISRG": "Intuitive Surgical Inc.",
    "ABNB": "Airbnb Inc.",
    "FIS": "Fidelity National Information Services Inc.",
    "FDX": "FedEx Corporation",
    "GM": "General Motors Company",
    "CI": "Cigna Corporation",
    "MMC": "Marsh & McLennan Companies Inc.",
    "ATVI": "Activision Blizzard Inc.",
    "RMD": "ResMed Inc.",
    "SPGI": "S&P Global Inc.",
    "ADSK": "Autodesk Inc.",
    "REGN": "Regeneron Pharmaceuticals Inc.",
    "EXC": "Exelon Corporation",
    "AON": "Aon plc",
    "WM": "Waste Management Inc.",
    "COO": "The Cooper Companies Inc.",
    "APD": "Air Products and Chemicals Inc.",
    "SYK": "Stryker Corporation",
    "BK": "The Bank of New York Mellon Corporation",
    "DXCM": "DexCom Inc.",
    "EA": "Electronic Arts Inc.",
    "DE": "Deere & Company",
    "HUM": "Humana Inc.",
    "SYY": "Sysco Corporation",
    "KLAC": "KLA Corporation",
    "ECL": "Ecolab Inc.",
    "ED": "Consolidated Edison Inc.",
    "ITW": "Illinois Tool Works Inc.",
    "DUK": "Duke Energy Corporation",
    "NSC": "Norfolk Southern Corporation",
    "ICE": "Intercontinental Exchange Inc.",
    "DD": "DuPont de Nemours Inc.",
    "NEM": "Newmont Corporation",
    "CTAS": "Cintas Corporation",
    "VRSK": "Verisk Analytics Inc.",
    "CDNS": "Cadence Design Systems Inc.",
    "ZBRA": "Zebra Technologies Corporation",
    "IDXX": "IDEXX Laboratories Inc.",
    "CPRT": "Copart Inc.",
    "SNPS": "Synopsys Inc.",
    "ALGN": "Align Technology Inc.",
    "ANSS": "ANSYS Inc.",
    "MKTX": "MarketAxess Holdings Inc.",
    "TGT": "Target Corporation",
    "FTNT": "Fortinet Inc.",
    "EFX": "Equifax Inc.",
    "PAYX": "Paychex Inc.",
    "MSCI": "MSCI Inc.",
    "ORLY": "O'Reilly Automotive Inc.",
    "SPG": "Simon Property Group Inc.",
    "CHD": "Church & Dwight Co. Inc.",
    "INFO": "IHS Markit Ltd.",
    "MCO": "Moody's Corporation",
    "RSG": "Republic Services Inc.",
    "AXP": "American Express Company",
    "VRTX": "Vertex Pharmaceuticals Incorporated",
    "ADS": "Alliance Data Systems Corporation",
    "DLTR": "Dollar Tree Inc.",
    "BLL": "Ball Corporation",
    "BIIB": "Biogen Inc.",
    "EW": "Edwards Lifesciences Corporation",
    "RMD": "ResMed Inc.",
    "ESS": "Essex Property Trust Inc.",
    "ROP": "Roper Technologies Inc.",
    "CTSH": "Cognizant Technology Solutions Corporation",
    "PGR": "The Progressive Corporation",
    "HCA": "HCA Healthcare Inc.",
    "IPGP": "IPG Photonics Corporation",
    "SRE": "Sempra Energy",
    "CARR": "Carrier Global Corporation",
    "LHX": "L3Harris Technologies Inc.",
    "NLOK": "NortonLifeLock Inc.",
    "WST": "West Pharmaceutical Services Inc.",
    "KEYS": "Keysight Technologies Inc.",
    "TRV": "The Travelers Companies Inc.",
    "PSA": "Public Storage",
    "NTAP": "NetApp Inc.",
    "NVR": "NVR Inc.",
    "A": "Agilent Technologies Inc.",
    "HLT": "Hilton Worldwide Holdings Inc.",
    "WDC": "Western Digital Corporation",
    "PHM": "PulteGroup Inc.",
    "ALB": "Albemarle Corporation",
    "BR": "Broadridge Financial Solutions Inc.",
    "EXPE": "Expedia Group Inc.",
    "AMAT": "Applied Materials Inc.",
    "WY": "Weyerhaeuser Company",
    "O": "Realty Income Corporation",
    "CCL": "Carnival Corporation & plc",
    "NDAQ": "Nasdaq Inc.",
    "XLNX": "Xilinx Inc.",
    "VLO": "Valero Energy Corporation",
    "REG": "Regency Centers Corporation",
    "NCLH": "Norwegian Cruise Line Holdings Ltd."
}

    # Replace stock symbols with unique names
    stock_data["stock_name"] = stock_data["stock_symbol"].map(symbol_mapping)

    return stock_data


@test
def test_output(output, *args) -> None:
    """
    Template code for testing the output of the block.
    """
    assert output is not None, 'The output is undefined'