version: 2

sources:
  - name: staging
    database: verdant-legacy-414217
    schema: stock_prices_dataset

    tables:
      - name: stock_price_data
        columns:
          - name: datetime
            tests:
              - not_null
              - unique
          - name: open
            tests:
              - not_null
          - name: high
            tests:
              - not_null
          - name: low
            tests:
              - not_null
          - name: close
            tests:
              - not_null
          - name: volume
            tests:
              - not_null
          - name: stock_symbol
            tests:
              - not_null
              - unique
          - name: stock_name
            tests:
              - not_null
              - unique
